// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pathfinder.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FlowRecord represents a network connection observed by an agent.
type FlowRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SrcIp         string                 `protobuf:"bytes,2,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	SrcPort       uint32                 `protobuf:"varint,3,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstIp         string                 `protobuf:"bytes,4,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	DstPort       uint32                 `protobuf:"varint,5,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"` // tcp, udp, etc.
	BytesSent     uint64                 `protobuf:"varint,7,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived uint64                 `protobuf:"varint,8,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,9,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	ProcessName   string                 `protobuf:"bytes,10,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	ProcessPid    uint32                 `protobuf:"varint,11,opt,name=process_pid,json=processPid,proto3" json:"process_pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowRecord) Reset() {
	*x = FlowRecord{}
	mi := &file_pathfinder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowRecord) ProtoMessage() {}

func (x *FlowRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowRecord.ProtoReflect.Descriptor instead.
func (*FlowRecord) Descriptor() ([]byte, []int) {
	return file_pathfinder_proto_rawDescGZIP(), []int{0}
}

func (x *FlowRecord) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *FlowRecord) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

func (x *FlowRecord) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *FlowRecord) GetDstIp() string {
	if x != nil {
		return x.DstIp
	}
	return ""
}

func (x *FlowRecord) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *FlowRecord) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *FlowRecord) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *FlowRecord) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *FlowRecord) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *FlowRecord) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *FlowRecord) GetProcessPid() uint32 {
	if x != nil {
		return x.ProcessPid
	}
	return 0
}

// AgentHeartbeat sent periodically by each agent.
type AgentHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsType        string                 `protobuf:"bytes,3,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"` // linux, windows, k8s
	AgentVersion  string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	TimestampNs   int64                  `protobuf:"varint,6,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHeartbeat) Reset() {
	*x = AgentHeartbeat{}
	mi := &file_pathfinder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeartbeat) ProtoMessage() {}

func (x *AgentHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeartbeat.ProtoReflect.Descriptor instead.
func (*AgentHeartbeat) Descriptor() ([]byte, []int) {
	return file_pathfinder_proto_rawDescGZIP(), []int{1}
}

func (x *AgentHeartbeat) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentHeartbeat) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentHeartbeat) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *AgentHeartbeat) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentHeartbeat) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *AgentHeartbeat) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

// EnrollmentRequest sent on first agent startup.
type EnrollmentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentToken string                 `protobuf:"bytes,1,opt,name=enrollment_token,json=enrollmentToken,proto3" json:"enrollment_token,omitempty"`
	Hostname        string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsType          string                 `protobuf:"bytes,3,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
	AgentVersion    string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrollmentRequest) Reset() {
	*x = EnrollmentRequest{}
	mi := &file_pathfinder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentRequest) ProtoMessage() {}

func (x *EnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentRequest.ProtoReflect.Descriptor instead.
func (*EnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_pathfinder_proto_rawDescGZIP(), []int{2}
}

func (x *EnrollmentRequest) GetEnrollmentToken() string {
	if x != nil {
		return x.EnrollmentToken
	}
	return ""
}

func (x *EnrollmentRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EnrollmentRequest) GetOsType() string {
	if x != nil {
		return x.OsType
	}
	return ""
}

func (x *EnrollmentRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type EnrollmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	GatewayCert   string                 `protobuf:"bytes,2,opt,name=gateway_cert,json=gatewayCert,proto3" json:"gateway_cert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollmentResponse) Reset() {
	*x = EnrollmentResponse{}
	mi := &file_pathfinder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentResponse) ProtoMessage() {}

func (x *EnrollmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentResponse.ProtoReflect.Descriptor instead.
func (*EnrollmentResponse) Descriptor() ([]byte, []int) {
	return file_pathfinder_proto_rawDescGZIP(), []int{3}
}

func (x *EnrollmentResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EnrollmentResponse) GetGatewayCert() string {
	if x != nil {
		return x.GatewayCert
	}
	return ""
}

type FlowBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flows         []*FlowRecord          `protobuf:"bytes,1,rep,name=flows,proto3" json:"flows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowBatch) Reset() {
	*x = FlowBatch{}
	mi := &file_pathfinder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowBatch) ProtoMessage() {}

func (x *FlowBatch) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowBatch.ProtoReflect.Descriptor instead.
func (*FlowBatch) Descriptor() ([]byte, []int) {
	return file_pathfinder_proto_rawDescGZIP(), []int{4}
}

func (x *FlowBatch) GetFlows() []*FlowRecord {
	if x != nil {
		return x.Flows
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_pathfinder_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_pathfinder_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_pathfinder_proto_rawDescGZIP(), []int{5}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pathfinder_proto protoreflect.FileDescriptor

const file_pathfinder_proto_rawDesc = "" +
	"\n" +
	"\x10pathfinder.proto\x12\n" +
	"pathfinder\"\xd4\x02\n" +
	"\n" +
	"FlowRecord\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x15\n" +
	"\x06src_ip\x18\x02 \x01(\tR\x05srcIp\x12\x19\n" +
	"\bsrc_port\x18\x03 \x01(\rR\asrcPort\x12\x15\n" +
	"\x06dst_ip\x18\x04 \x01(\tR\x05dstIp\x12\x19\n" +
	"\bdst_port\x18\x05 \x01(\rR\adstPort\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\tR\bprotocol\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\a \x01(\x04R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\b \x01(\x04R\rbytesReceived\x12!\n" +
	"\ftimestamp_ns\x18\t \x01(\x03R\vtimestampNs\x12!\n" +
	"\fprocess_name\x18\n" +
	" \x01(\tR\vprocessName\x12\x1f\n" +
	"\vprocess_pid\x18\v \x01(\rR\n" +
	"processPid\"\xcf\x01\n" +
	"\x0eAgentHeartbeat\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x17\n" +
	"\aos_type\x18\x03 \x01(\tR\x06osType\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x03R\ruptimeSeconds\x12!\n" +
	"\ftimestamp_ns\x18\x06 \x01(\x03R\vtimestampNs\"\x98\x01\n" +
	"\x11EnrollmentRequest\x12)\n" +
	"\x10enrollment_token\x18\x01 \x01(\tR\x0fenrollmentToken\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x17\n" +
	"\aos_type\x18\x03 \x01(\tR\x06osType\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\"R\n" +
	"\x12EnrollmentResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12!\n" +
	"\fgateway_cert\x18\x02 \x01(\tR\vgatewayCert\"9\n" +
	"\tFlowBatch\x12,\n" +
	"\x05flows\x18\x01 \x03(\v2\x16.pathfinder.FlowRecordR\x05flows\"9\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xcd\x01\n" +
	"\x11PathfinderGateway\x12G\n" +
	"\x06Enroll\x12\x1d.pathfinder.EnrollmentRequest\x1a\x1e.pathfinder.EnrollmentResponse\x125\n" +
	"\tSendFlows\x12\x15.pathfinder.FlowBatch\x1a\x0f.pathfinder.Ack(\x01\x128\n" +
	"\tHeartbeat\x12\x1a.pathfinder.AgentHeartbeat\x1a\x0f.pathfinder.AckB+Z)github.com/blmuffley/Pathfinder/src/protob\x06proto3"

var (
	file_pathfinder_proto_rawDescOnce sync.Once
	file_pathfinder_proto_rawDescData []byte
)

func file_pathfinder_proto_rawDescGZIP() []byte {
	file_pathfinder_proto_rawDescOnce.Do(func() {
		file_pathfinder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pathfinder_proto_rawDesc), len(file_pathfinder_proto_rawDesc)))
	})
	return file_pathfinder_proto_rawDescData
}

var file_pathfinder_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pathfinder_proto_goTypes = []any{
	(*FlowRecord)(nil),         // 0: pathfinder.FlowRecord
	(*AgentHeartbeat)(nil),     // 1: pathfinder.AgentHeartbeat
	(*EnrollmentRequest)(nil),  // 2: pathfinder.EnrollmentRequest
	(*EnrollmentResponse)(nil), // 3: pathfinder.EnrollmentResponse
	(*FlowBatch)(nil),          // 4: pathfinder.FlowBatch
	(*Ack)(nil),                // 5: pathfinder.Ack
}
var file_pathfinder_proto_depIdxs = []int32{
	0, // 0: pathfinder.FlowBatch.flows:type_name -> pathfinder.FlowRecord
	2, // 1: pathfinder.PathfinderGateway.Enroll:input_type -> pathfinder.EnrollmentRequest
	4, // 2: pathfinder.PathfinderGateway.SendFlows:input_type -> pathfinder.FlowBatch
	1, // 3: pathfinder.PathfinderGateway.Heartbeat:input_type -> pathfinder.AgentHeartbeat
	3, // 4: pathfinder.PathfinderGateway.Enroll:output_type -> pathfinder.EnrollmentResponse
	5, // 5: pathfinder.PathfinderGateway.SendFlows:output_type -> pathfinder.Ack
	5, // 6: pathfinder.PathfinderGateway.Heartbeat:output_type -> pathfinder.Ack
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pathfinder_proto_init() }
func file_pathfinder_proto_init() {
	if File_pathfinder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pathfinder_proto_rawDesc), len(file_pathfinder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pathfinder_proto_goTypes,
		DependencyIndexes: file_pathfinder_proto_depIdxs,
		MessageInfos:      file_pathfinder_proto_msgTypes,
	}.Build()
	File_pathfinder_proto = out.File
	file_pathfinder_proto_goTypes = nil
	file_pathfinder_proto_depIdxs = nil
}
