// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: pathfinder.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PathfinderGateway_Enroll_FullMethodName    = "/pathfinder.PathfinderGateway/Enroll"
	PathfinderGateway_SendFlows_FullMethodName = "/pathfinder.PathfinderGateway/SendFlows"
	PathfinderGateway_Heartbeat_FullMethodName = "/pathfinder.PathfinderGateway/Heartbeat"
)

// PathfinderGatewayClient is the client API for PathfinderGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PathfinderGateway is the core gRPC service agents connect to.
type PathfinderGatewayClient interface {
	Enroll(ctx context.Context, in *EnrollmentRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error)
	SendFlows(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FlowBatch, Ack], error)
	Heartbeat(ctx context.Context, in *AgentHeartbeat, opts ...grpc.CallOption) (*Ack, error)
}

type pathfinderGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewPathfinderGatewayClient(cc grpc.ClientConnInterface) PathfinderGatewayClient {
	return &pathfinderGatewayClient{cc}
}

func (c *pathfinderGatewayClient) Enroll(ctx context.Context, in *EnrollmentRequest, opts ...grpc.CallOption) (*EnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollmentResponse)
	err := c.cc.Invoke(ctx, PathfinderGateway_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pathfinderGatewayClient) SendFlows(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FlowBatch, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PathfinderGateway_ServiceDesc.Streams[0], PathfinderGateway_SendFlows_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FlowBatch, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PathfinderGateway_SendFlowsClient = grpc.ClientStreamingClient[FlowBatch, Ack]

func (c *pathfinderGatewayClient) Heartbeat(ctx context.Context, in *AgentHeartbeat, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, PathfinderGateway_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PathfinderGatewayServer is the server API for PathfinderGateway service.
// All implementations must embed UnimplementedPathfinderGatewayServer
// for forward compatibility.
//
// PathfinderGateway is the core gRPC service agents connect to.
type PathfinderGatewayServer interface {
	Enroll(context.Context, *EnrollmentRequest) (*EnrollmentResponse, error)
	SendFlows(grpc.ClientStreamingServer[FlowBatch, Ack]) error
	Heartbeat(context.Context, *AgentHeartbeat) (*Ack, error)
	mustEmbedUnimplementedPathfinderGatewayServer()
}

// UnimplementedPathfinderGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPathfinderGatewayServer struct{}

func (UnimplementedPathfinderGatewayServer) Enroll(context.Context, *EnrollmentRequest) (*EnrollmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedPathfinderGatewayServer) SendFlows(grpc.ClientStreamingServer[FlowBatch, Ack]) error {
	return status.Error(codes.Unimplemented, "method SendFlows not implemented")
}
func (UnimplementedPathfinderGatewayServer) Heartbeat(context.Context, *AgentHeartbeat) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedPathfinderGatewayServer) mustEmbedUnimplementedPathfinderGatewayServer() {}
func (UnimplementedPathfinderGatewayServer) testEmbeddedByValue()                           {}

// UnsafePathfinderGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PathfinderGatewayServer will
// result in compilation errors.
type UnsafePathfinderGatewayServer interface {
	mustEmbedUnimplementedPathfinderGatewayServer()
}

func RegisterPathfinderGatewayServer(s grpc.ServiceRegistrar, srv PathfinderGatewayServer) {
	// If the following call panics, it indicates UnimplementedPathfinderGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PathfinderGateway_ServiceDesc, srv)
}

func _PathfinderGateway_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PathfinderGatewayServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PathfinderGateway_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PathfinderGatewayServer).Enroll(ctx, req.(*EnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PathfinderGateway_SendFlows_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PathfinderGatewayServer).SendFlows(&grpc.GenericServerStream[FlowBatch, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PathfinderGateway_SendFlowsServer = grpc.ClientStreamingServer[FlowBatch, Ack]

func _PathfinderGateway_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentHeartbeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PathfinderGatewayServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PathfinderGateway_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PathfinderGatewayServer).Heartbeat(ctx, req.(*AgentHeartbeat))
	}
	return interceptor(ctx, in, info, handler)
}

// PathfinderGateway_ServiceDesc is the grpc.ServiceDesc for PathfinderGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PathfinderGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pathfinder.PathfinderGateway",
	HandlerType: (*PathfinderGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _PathfinderGateway_Enroll_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _PathfinderGateway_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendFlows",
			Handler:       _PathfinderGateway_SendFlows_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pathfinder.proto",
}
